version: '2'
services: 
    # zookeeper:
    #     container_name: zookeeper
    #     image: confluentinc/cp-zookeeper:latest
    #     environment: 
    #         ZOOKEEPER_CLIENT_PORT: 2181
    
    # kafka:
    #     container_name: broker
    #     image: confluentinc/cp-kafka:latest
    #     depends_on: 
    #         - zookeeper
    #     ports: 
    #         - 9092:9092
    #     environment: 
    #         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    #         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    # kowl:
    #     container_name: kowl
    #     image: quay.io/cloudhut/kowl:master
    #     depends_on:
    #         - kafka
    #     ports:
    #         - 8080:8080
    #     environment:
    #         KAFKA_BROKERS: localhost:9092

    db:
        container_name: postgres
        image: postgres
        # depends_on: 
        #     - kafka
        environment:
            POSTGRES_PASSWORD: "123"
        ports:
            - 5432:5432
