version: '2'
services: 
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment: 
            ZOOKEEPER_CLIENT_PORT: 2181
    
    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on: 
            - zookeeper
        ports: 
            - 9092:9092
        environment: 
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
    db:
        image: postgres
        depends_on: 
            - kafka
        environment:
            POSTGRES_PASSWORD: "123"
        ports:
            - 5432:5432
            
    # kafka-ui:
    #     image: provectuslabs/kafka-ui
    #     container_name: kafka-ui
    #     ports:
    #     - "8080:8080"
    #     restart: always
    #     environment:
    #     - KAFKA_CLUSTERS_0_NAME=local
    #     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

    # pgadmin:
    #     container_name: pgadmin4
    #     image: dpage/pgadmin4
    #     restart: always
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
    #         PGADMIN_DEFAULT_PASSWORD: "root"
    #     ports:
    #     - "5050:80"